version: '3'

services:
  app:
    build: .
    env_file: .env
    environment:
      RAILS_ENV: production
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - web-root:/pixnyannyan/public
      - web-log:/pixnyannyan/log
  db:
    image: postgres:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:3-alpine

volumes:
  db-data:
  web-root:
  web-log:
