##
# Constants used in PixNyanNyan
##

# Content limit
MAX_IMAGE_SIZE = ENV.fetch('MAX_IMAGE_KB_SIZE'){ 5120 }.to_i.kilobytes
MAX_POST_MESSAGE_WORDCOUNT = ENV.fetch('MAX_POST_MESSAGE_WORDCOUNT'){ 1000 }.to_i

PHASH_THRESHOLD = ENV.fetch('PHASH_THRESHOLD'){ 15 }.to_i
MAX_RECORD_PER_QUERY = ENV.fetch('MAX_RECORD_PER_QUERY'){ 10 }.to_i
MAX_PREVIEW_PER_THREAD = ENV.fetch('MAX_PREVIEW_PER_THREAD'){ 5 }.to_i