version: '2'

services:
  web:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    depends_on:
      - app
    volumes:
      - web-root:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
  app:
    image: atitan/pixnyannyan-api:latest
    env_file: .env
    environment:
      RAILS_ENV: production
    depends_on:
      - db
      - redis
    volumes:
      - web-root:/pixnyannyan/public
      - web-log:/pixnyannyan/log
    restart: always
  db:
    image: atitan/pixnyannyan-postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:3-alpine
    restart: always

volumes:
  db-data:
  web-root:
  web-log:
